Fix: doc/examples/java-jul: fix paths to directories
I tried to run this example, but got:

    $ ./run
    Error: Unable to initialize main class Hello
    Caused by: java.lang.NoClassDefFoundError: org/lttng/ust/agent/jul/LttngLogHandler

The paths in `run` are wrong, they are missing a `src` component.  Fix
that.

Change-Id: I63f4532c5ec1d989f66b7061a154986692e2edf9
Signed-off-by: Simon Marchi <simon.marchi@efficios.com>
Signed-off-by: Mathieu Desnoyers <mathieu.desnoyers@efficios.com>