Fix: allocate ts_end in ringbuffer shared memory
Allocate the memory used by the ts_end field added by commit 6c737d05.
When allocating lots of subbuffer for a channel (512 or more),
zalloc_shm() will fail to allocate all the objects because the allocated
memory map didn't take account the newly added field.

With lttng-tools version: b14f53d4 (2.12.0-pre)

Steps to reproduce the bug:

	1. lttng-sessiond -vvv --verbose-consumer
	2. start a traced application
	3. lttng create "test-sesssion"
	4. lttng enable-channel --userspace --num-subbuf 512 \
                                --subbuf-size 8k --overwrite channel
	5. lttng enable-event -u -a -c channel
	6. lttng start

After these steps, the following error message show should be thrown:

	Error: ask_channel_creation consumer command failed
	Error: Error creating UST channel "channel" on the consumer daemon

Signed-off-by: Gabriel-Andrew Pollo-Guilbert <gabriel.pollo-guilbert@efficios.com>
Signed-off-by: Mathieu Desnoyers <mathieu.desnoyers@efficios.com>